# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-21 07:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authentication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=256, unique=True)),
                ('password', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'authentication',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('salutation', models.CharField(max_length=128, null=True)),
                ('first_name', models.CharField(max_length=256, null=True)),
                ('last_name', models.CharField(max_length=256, null=True)),
                ('email', models.CharField(max_length=512, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('relationship_status', models.CharField(max_length=128, null=True)),
                ('gender', models.CharField(max_length=128, null=True)),
                ('authentication', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='management_system.Authentication')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(null=True)),
                ('label', models.CharField(max_length=128, null=True)),
                ('nearest_landmark', models.CharField(max_length=512, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management_system.User')),
            ],
            options={
                'db_table': 'user_address',
            },
        ),
    ]
