# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-21 09:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_system', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authentication',
            old_name='username',
            new_name='email',
        ),
    ]
