# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-28 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_system', '0003_auto_20180724_0431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
